name: Word of the Day Bot

on:
  schedule:
    - cron: "52 17 * * *"  # Runs at 8:00 AM IST (2:30 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-telegram-bot requests python-dotenv

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
        run: python telegram-bot.py
